-- ============================================================
-- 009 - Campaign Orchestrator / jobs persistants
-- PostgreSQL 17
--
-- Objectifs:
-- - le POST /campagnes ne bloque plus pendant le peuplement massif;
-- - les travaux lourds sont repris après crash/redémarrage;
-- - plusieurs workers peuvent coexister via FOR UPDATE SKIP LOCKED;
-- - l'état métier visible de la campagne reste indépendant de son état technique.
-- ============================================================

BEGIN;

ALTER TABLE campagnes
    ADD COLUMN IF NOT EXISTS execution_status TEXT NOT NULL DEFAULT 'ready',
    ADD COLUMN IF NOT EXISTS execution_error TEXT,
    ADD COLUMN IF NOT EXISTS preparation_started_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS preparation_finished_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS target_count_initial BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS target_count_eligible BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS population_count BIGINT NOT NULL DEFAULT 0;

UPDATE campagnes
SET execution_status = 'ready'
WHERE execution_status IS NULL OR BTRIM(execution_status) = '';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ck_campagnes_execution_status'
    ) THEN
        ALTER TABLE campagnes
            ADD CONSTRAINT ck_campagnes_execution_status
            CHECK (execution_status IN ('preparing','processing','ready','failed','cancelled'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_campagnes_execution_status
    ON campagnes (execution_status, etat_campagne, date_debut, date_fin);

CREATE TABLE IF NOT EXISTS orchestration_jobs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_key             TEXT NOT NULL UNIQUE,
    job_type            TEXT NOT NULL,
    priority            SMALLINT NOT NULL DEFAULT 100,
    status              TEXT NOT NULL DEFAULT 'pending',
    id_campagne         TEXT,
    payload             JSONB NOT NULL DEFAULT '{}'::jsonb,
    attempts            INTEGER NOT NULL DEFAULT 0,
    max_attempts        INTEGER NOT NULL DEFAULT 3,
    available_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    locked_at           TIMESTAMPTZ,
    locked_by           TEXT,
    heartbeat_at        TIMESTAMPTZ,
    cancel_requested    BOOLEAN NOT NULL DEFAULT FALSE,
    progress_current    BIGINT NOT NULL DEFAULT 0,
    progress_total      BIGINT NOT NULL DEFAULT 0,
    progress_message    TEXT,
    last_error          TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at         TIMESTAMPTZ,
    CONSTRAINT ck_orchestration_jobs_status CHECK (
        status IN ('pending','processing','retry','succeeded','failed','cancelled')
    )
);

CREATE INDEX IF NOT EXISTS idx_orchestration_jobs_claim
    ON orchestration_jobs (priority, available_at, id)
    WHERE status IN ('pending','retry');

CREATE INDEX IF NOT EXISTS idx_orchestration_jobs_campaign
    ON orchestration_jobs (id_campagne, status, id);

CREATE INDEX IF NOT EXISTS idx_orchestration_jobs_processing
    ON orchestration_jobs (locked_at, id)
    WHERE status = 'processing';

COMMIT;

ANALYZE campagnes;
ANALYZE orchestration_jobs;
