-- Etat technique minimal de publication d'une action externe.
ALTER TABLE clients_campagnes
    ADD COLUMN IF NOT EXISTS action_execution_seq BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS outbound_enqueued_key TEXT;

-- Outbox durable générique. Elle ne contient que les références nécessaires :
-- les données client/payload sont résolues au moment de l'envoi afin d'éviter
-- de dupliquer les données du datamart dans la plateforme.
CREATE TABLE IF NOT EXISTS outbound_dispatches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_campaign_id BIGINT,
    id_campagne TEXT NOT NULL,
    radical_compte TEXT NOT NULL,
    block_id TEXT NOT NULL,
    occurrence BIGINT NOT NULL DEFAULT 0,
    channel TEXT NOT NULL,
    provider TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    priority INTEGER NOT NULL DEFAULT 100,
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    locked_at TIMESTAMPTZ,
    heartbeat_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    provider_reference TEXT,
    payload_json JSONB,
    response_json JSONB,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (id_campagne, radical_compte, block_id, occurrence, channel)
);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_outbound_claim
    ON outbound_dispatches (channel, status, available_at, priority, id)
    WHERE status IN ('pending', 'retry', 'processing');

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_outbound_campaign_status
    ON outbound_dispatches (id_campagne, status, channel);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_outbound_waiting_callback
    ON outbound_dispatches (id_campagne, radical_compte, block_id, status)
    WHERE status IN ('sent', 'waiting_callback');

-- Le producteur ne scanne que les lignes dont l'action courante n'a pas encore
-- été publiée. L'expression clé change automatiquement quand le bloc ou son
-- occurrence change.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cc_outbound_mail_candidates
    ON clients_campagnes (id, "ID_CAMPAGNE")
    WHERE COALESCE("Etat_campagne", '') = 'En cours'
      AND COALESCE(conversion, 0) <> 1
      AND COALESCE("Canal", '') = 'Mail'
      AND COALESCE("Action", '') IN ('Message', 'Mail');

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cc_outbound_terrain_candidates
    ON clients_campagnes (id, "ID_CAMPAGNE")
    WHERE COALESCE("Etat_campagne", '') = 'En cours'
      AND COALESCE(conversion, 0) <> 1
      AND COALESCE("Action", '') IN ('Directeur d''agence', 'Conseiller client');

-- Inbox durable générique pour callbacks/événements entrants.
CREATE TABLE IF NOT EXISTS inbound_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key TEXT NOT NULL UNIQUE,
    channel TEXT NOT NULL,
    event_type TEXT NOT NULL,
    id_campagne TEXT,
    radical_compte TEXT,
    block_id TEXT,
    payload_json JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    locked_at TIMESTAMPTZ,
    processed_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_inbound_claim
    ON inbound_events (status, available_at, id)
    WHERE status IN ('pending', 'retry', 'processing');

-- Backfill non destructif des visites historiques encore actives.
INSERT INTO outbound_dispatches (
    id_campagne, radical_compte, block_id, occurrence, channel, provider,
    status, attempts, max_attempts, available_at, sent_at, payload_json,
    last_error, created_at, updated_at
)
SELECT
    e.id_campagne,
    e.radical_compte,
    e.block_id,
    0,
    'TERRAIN',
    'VISITS_API',
    CASE
        WHEN e.status = 'sent' THEN 'waiting_callback'
        WHEN e.status = 'processing' THEN 'retry'
        WHEN e.status = 'error' THEN 'retry'
        WHEN e.status = 'pending' THEN 'pending'
        ELSE 'cancelled'
    END,
    COALESCE(e.attempts, 0),
    5,
    NOW(),
    CASE WHEN e.sent_at IS NOT NULL AND e.sent_at <> '' THEN NOW() ELSE NULL END,
    CASE
        WHEN e.payload_json IS NULL OR BTRIM(e.payload_json) = '' THEN NULL
        ELSE jsonb_build_object('legacy_payload', e.payload_json)
    END,
    e.error,
    NOW(),
    NOW()
FROM external_visit_dispatches e
WHERE e.status IN ('pending', 'processing', 'error', 'sent')
ON CONFLICT (id_campagne, radical_compte, block_id, occurrence, channel) DO NOTHING;

ANALYZE outbound_dispatches;
ANALYZE inbound_events;
ANALYZE clients_campagnes;

