BEGIN;

-- ============================================================
-- Best Channel - MVP
--
-- - Canal_top1/2/3 exposent le dernier classement exploitable par les cibles.
-- - dm_best_channel_interactions conserve 12 mois d'historique bloc-par-bloc.
-- - dm_best_channel_scores historise les scorings semestriels par client.
-- - best_channel_sequence_no permet de séparer les séquences entre objectifs.
-- ============================================================

ALTER TABLE clients
    ADD COLUMN IF NOT EXISTS "Canal_top1" TEXT NOT NULL DEFAULT 'non_score';
ALTER TABLE clients
    ADD COLUMN IF NOT EXISTS "Canal_top2" TEXT NOT NULL DEFAULT 'non_score';
ALTER TABLE clients
    ADD COLUMN IF NOT EXISTS "Canal_top3" TEXT NOT NULL DEFAULT 'non_score';

CREATE INDEX IF NOT EXISTS idx_clients_canal_top1 ON clients ("Canal_top1");
CREATE INDEX IF NOT EXISTS idx_clients_canal_top2 ON clients ("Canal_top2");
CREATE INDEX IF NOT EXISTS idx_clients_canal_top3 ON clients ("Canal_top3");

ALTER TABLE clients_campagnes
    ADD COLUMN IF NOT EXISTS best_channel_sequence_no INTEGER NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS dm_best_channel_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL DEFAULT 'reel',
    id_campagne TEXT NOT NULL,
    radical_compte TEXT NOT NULL,
    sequence_no INTEGER NOT NULL DEFAULT 1,
    block_id TEXT NOT NULL,
    block_order INTEGER NOT NULL DEFAULT 1,
    action_execution_seq BIGINT NOT NULL DEFAULT 0,
    canal TEXT NOT NULL,
    message TEXT,
    resultat_bloc TEXT,
    qualite_resultat DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    objectif_valide SMALLINT NOT NULL DEFAULT 0,
    objectif_id_action TEXT,
    tranche_age TEXT,
    region TEXT,
    observed_at TIMESTAMPTZ NOT NULL,
    finalized_at TIMESTAMPTZ,
    event_key TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_best_channel_interactions_source
        CHECK (source IN ('fake', 'reel')),
    CONSTRAINT ck_best_channel_interactions_objectif
        CHECK (objectif_valide IN (0, 1)),
    CONSTRAINT ck_best_channel_interactions_qualite
        CHECK (qualite_resultat >= 0 AND qualite_resultat <= 1),
    CONSTRAINT ck_best_channel_interactions_sequence
        CHECK (sequence_no >= 1),
    CONSTRAINT ck_best_channel_interactions_order
        CHECK (block_order >= 1)
);

CREATE INDEX IF NOT EXISTS idx_best_channel_interactions_date
    ON dm_best_channel_interactions (observed_at);
CREATE INDEX IF NOT EXISTS idx_best_channel_interactions_training
    ON dm_best_channel_interactions (finalized_at, objectif_valide, observed_at);
CREATE INDEX IF NOT EXISTS idx_best_channel_interactions_client
    ON dm_best_channel_interactions (radical_compte, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_best_channel_interactions_sequence
    ON dm_best_channel_interactions (id_campagne, radical_compte, sequence_no);
CREATE INDEX IF NOT EXISTS idx_best_channel_interactions_canal
    ON dm_best_channel_interactions (canal, observed_at DESC);

CREATE TABLE IF NOT EXISTS dm_best_channel_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    radical_compte TEXT NOT NULL,
    date_scoring DATE NOT NULL,
    annee_mois INTEGER NOT NULL,
    statut_client_snapshot TEXT,
    tranche_age TEXT,
    region TEXT,

    canal_top1 TEXT NOT NULL,
    score_top1 DOUBLE PRECISION NOT NULL,
    canal_top2 TEXT NOT NULL,
    score_top2 DOUBLE PRECISION NOT NULL,
    canal_top3 TEXT NOT NULL,
    score_top3 DOUBLE PRECISION NOT NULL,

    modele TEXT NOT NULL DEFAULT 'best_channel_xgboost_v1',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_best_channel_score_client_date UNIQUE (radical_compte, date_scoring),
    CONSTRAINT ck_best_channel_score_top1 CHECK (score_top1 >= 0 AND score_top1 <= 1),
    CONSTRAINT ck_best_channel_score_top2 CHECK (score_top2 >= 0 AND score_top2 <= 1),
    CONSTRAINT ck_best_channel_score_top3 CHECK (score_top3 >= 0 AND score_top3 <= 1)
);

CREATE INDEX IF NOT EXISTS idx_best_channel_scores_client_date
    ON dm_best_channel_scores (radical_compte, date_scoring DESC);
CREATE INDEX IF NOT EXISTS idx_best_channel_scores_period
    ON dm_best_channel_scores (annee_mois);
CREATE INDEX IF NOT EXISTS idx_best_channel_scores_top1
    ON dm_best_channel_scores (canal_top1, date_scoring DESC);

COMMIT;
