BEGIN;

-- ============================================================
-- Pression commerciale
--
-- Score absolu calculé mensuellement sur les 30 derniers jours.
-- La valeur courante est copiée dans clients pour les cibles et
-- l'historique mensuel est conservé dans une table dédiée.
-- ============================================================

ALTER TABLE clients
    ADD COLUMN IF NOT EXISTS "Pression_commerciale" TEXT NOT NULL DEFAULT 'non_score';

ALTER TABLE clients
    DROP CONSTRAINT IF EXISTS ck_clients_pression_commerciale_values;
ALTER TABLE clients
    ADD CONSTRAINT ck_clients_pression_commerciale_values
    CHECK ("Pression_commerciale" IN ('Faible', 'Modere', 'Eleve', 'non_score'));

CREATE INDEX IF NOT EXISTS idx_clients_pression_commerciale
    ON clients ("Pression_commerciale");

CREATE TABLE IF NOT EXISTS dm_commercial_pressure_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    radical_compte TEXT NOT NULL,
    date_scoring DATE NOT NULL,
    annee_mois INTEGER NOT NULL,
    window_start DATE NOT NULL,
    window_end DATE NOT NULL,
    statut_client_snapshot TEXT,
    region TEXT,

    score_pression DOUBLE PRECISION NOT NULL DEFAULT 0,
    niveau_pression TEXT NOT NULL,
    regle_niveau TEXT NOT NULL DEFAULT 'score',

    nb_actions_7j INTEGER NOT NULL DEFAULT 0,
    nb_actions_30j INTEGER NOT NULL DEFAULT 0,
    nb_interactions_humaines_7j INTEGER NOT NULL DEFAULT 0,
    nb_canaux_7j INTEGER NOT NULL DEFAULT 0,
    nb_canaux_30j INTEGER NOT NULL DEFAULT 0,
    dernier_contact TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_commercial_pressure_client_month UNIQUE (radical_compte, annee_mois),
    CONSTRAINT ck_commercial_pressure_score CHECK (score_pression >= 0),
    CONSTRAINT ck_commercial_pressure_level
        CHECK (niveau_pression IN ('Faible', 'Modere', 'Eleve')),
    CONSTRAINT ck_commercial_pressure_counts CHECK (
        nb_actions_7j >= 0
        AND nb_actions_30j >= 0
        AND nb_interactions_humaines_7j >= 0
        AND nb_canaux_7j >= 0
        AND nb_canaux_30j >= 0
    )
);

CREATE INDEX IF NOT EXISTS idx_commercial_pressure_scores_period
    ON dm_commercial_pressure_scores (annee_mois, niveau_pression);
CREATE INDEX IF NOT EXISTS idx_commercial_pressure_scores_client
    ON dm_commercial_pressure_scores (radical_compte, annee_mois DESC);
CREATE INDEX IF NOT EXISTS idx_commercial_pressure_scores_region
    ON dm_commercial_pressure_scores (annee_mois, region, niveau_pression);

COMMIT;
